###
GET {{host}}/api/Genres?page=1&pageSize=2

###
POST {{host}}/api/Genres
Content-Type: application/json

{
  "name": "Thriller"
}

###
GET {{host}}/api/Genres/1

###
PUT {{host}}/api/Genres/1
Content-Type: application/json

{
  "id": 1,
  "name": "Horror"
}

###
DELETE {{host}}/api/Genres/8