###
GET {{host}}/api/Users?page=1&pageSize=2

###
POST {{host}}/api/Users
Content-Type: application/json

{
  "email": "nikola@example.com",
  "password": "12345",
  "firstName": "Nikola",
  "lastName": "Pivcevic"
}

###
GET {{host}}/api/Users/1

###
PUT {{host}}/api/Users/1
Content-Type: application/json

{
  "id": 1,
  "email": "nikola@example.com",
  "password": "12345",
  "firstName": "Nikola",
  "lastName": "Pivcevic"
}

###
DELETE {{host}}/api/Users/1
